[package]
name = "secp256k1"
version = "0.1.0"
authors = ["ross <ross.pure@gmail.com>"]
edition = "2018"

build = "build.rs"
[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
rand = "0.7.3"
